//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloConsoleApp.WcfServiceHost {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfServiceHost.ICarService")]
    public interface ICarService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/GetMessageString", ReplyAction="http://tempuri.org/ICarService/GetMessageStringResponse")]
        string GetMessageString(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/GetMessageString", ReplyAction="http://tempuri.org/ICarService/GetMessageStringResponse")]
        System.Threading.Tasks.Task<string> GetMessageStringAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/GetMessageInt", ReplyAction="http://tempuri.org/ICarService/GetMessageIntResponse")]
        int GetMessageInt(int name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/GetMessageInt", ReplyAction="http://tempuri.org/ICarService/GetMessageIntResponse")]
        System.Threading.Tasks.Task<int> GetMessageIntAsync(int name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICarServiceChannel : HelloConsoleApp.WcfServiceHost.ICarService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarServiceClient : System.ServiceModel.ClientBase<HelloConsoleApp.WcfServiceHost.ICarService>, HelloConsoleApp.WcfServiceHost.ICarService {
        
        public CarServiceClient() {
        }
        
        public CarServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMessageString(string name) {
            return base.Channel.GetMessageString(name);
        }
        
        public System.Threading.Tasks.Task<string> GetMessageStringAsync(string name) {
            return base.Channel.GetMessageStringAsync(name);
        }
        
        public int GetMessageInt(int name) {
            return base.Channel.GetMessageInt(name);
        }
        
        public System.Threading.Tasks.Task<int> GetMessageIntAsync(int name) {
            return base.Channel.GetMessageIntAsync(name);
        }
    }
}
