//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWebClient.WcfServiceCustomerHost {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/Domain")]
    [System.SerializableAttribute()]
    public partial class Customer : HelloWebClient.WcfServiceCustomerHost.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HelloWebClient.WcfServiceCustomerHost.Booking[] BookingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HelloWebClient.WcfServiceCustomerHost.Booking[] Bookings {
            get {
                return this.BookingsField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingsField, value) != true)) {
                    this.BookingsField = value;
                    this.RaisePropertyChanged("Bookings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tel {
            get {
                return this.TelField;
            }
            set {
                if ((this.TelField.Equals(value) != true)) {
                    this.TelField = value;
                    this.RaisePropertyChanged("Tel");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Domain")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HelloWebClient.WcfServiceCustomerHost.Car))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HelloWebClient.WcfServiceCustomerHost.Booking))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HelloWebClient.WcfServiceCustomerHost.Customer))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnUtcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOnUtc {
            get {
                return this.CreatedOnUtcField;
            }
            set {
                if ((this.CreatedOnUtcField.Equals(value) != true)) {
                    this.CreatedOnUtcField = value;
                    this.RaisePropertyChanged("CreatedOnUtc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car", Namespace="http://schemas.datacontract.org/2004/07/Domain")]
    [System.SerializableAttribute()]
    public partial class Car : HelloWebClient.WcfServiceCustomerHost.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AvaliableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HelloWebClient.WcfServiceCustomerHost.Booking[] BookingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistrationNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Avaliable {
            get {
                return this.AvaliableField;
            }
            set {
                if ((this.AvaliableField.Equals(value) != true)) {
                    this.AvaliableField = value;
                    this.RaisePropertyChanged("Avaliable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HelloWebClient.WcfServiceCustomerHost.Booking[] Bookings {
            get {
                return this.BookingsField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingsField, value) != true)) {
                    this.BookingsField = value;
                    this.RaisePropertyChanged("Bookings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegistrationNumber {
            get {
                return this.RegistrationNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationNumberField, value) != true)) {
                    this.RegistrationNumberField = value;
                    this.RaisePropertyChanged("RegistrationNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Year {
            get {
                return this.YearField;
            }
            set {
                if ((this.YearField.Equals(value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Booking", Namespace="http://schemas.datacontract.org/2004/07/Domain")]
    [System.SerializableAttribute()]
    public partial class Booking : HelloWebClient.WcfServiceCustomerHost.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HelloWebClient.WcfServiceCustomerHost.Car CarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CarIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HelloWebClient.WcfServiceCustomerHost.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HelloWebClient.WcfServiceCustomerHost.Car Car {
            get {
                return this.CarField;
            }
            set {
                if ((object.ReferenceEquals(this.CarField, value) != true)) {
                    this.CarField = value;
                    this.RaisePropertyChanged("Car");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarID {
            get {
                return this.CarIDField;
            }
            set {
                if ((this.CarIDField.Equals(value) != true)) {
                    this.CarIDField = value;
                    this.RaisePropertyChanged("CarID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HelloWebClient.WcfServiceCustomerHost.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfServiceCustomerHost.IServiceCustomer")]
    public interface IServiceCustomer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCustomer/AddCustomer", ReplyAction="http://tempuri.org/IServiceCustomer/AddCustomerResponse")]
        void AddCustomer(string fName, string lName, string eMail, int tel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCustomer/AddCustomer", ReplyAction="http://tempuri.org/IServiceCustomer/AddCustomerResponse")]
        System.Threading.Tasks.Task AddCustomerAsync(string fName, string lName, string eMail, int tel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCustomer/GetCustomerList", ReplyAction="http://tempuri.org/IServiceCustomer/GetCustomerListResponse")]
        HelloWebClient.WcfServiceCustomerHost.Customer[] GetCustomerList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCustomer/GetCustomerList", ReplyAction="http://tempuri.org/IServiceCustomer/GetCustomerListResponse")]
        System.Threading.Tasks.Task<HelloWebClient.WcfServiceCustomerHost.Customer[]> GetCustomerListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCustomer/GetCustomerByLastName", ReplyAction="http://tempuri.org/IServiceCustomer/GetCustomerByLastNameResponse")]
        HelloWebClient.WcfServiceCustomerHost.Customer GetCustomerByLastName(string lName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCustomer/GetCustomerByLastName", ReplyAction="http://tempuri.org/IServiceCustomer/GetCustomerByLastNameResponse")]
        System.Threading.Tasks.Task<HelloWebClient.WcfServiceCustomerHost.Customer> GetCustomerByLastNameAsync(string lName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCustomer/GetCustomerById", ReplyAction="http://tempuri.org/IServiceCustomer/GetCustomerByIdResponse")]
        HelloWebClient.WcfServiceCustomerHost.Customer GetCustomerById(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCustomer/GetCustomerById", ReplyAction="http://tempuri.org/IServiceCustomer/GetCustomerByIdResponse")]
        System.Threading.Tasks.Task<HelloWebClient.WcfServiceCustomerHost.Customer> GetCustomerByIdAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCustomer/UpdateCustomer", ReplyAction="http://tempuri.org/IServiceCustomer/UpdateCustomerResponse")]
        void UpdateCustomer(HelloWebClient.WcfServiceCustomerHost.Customer x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCustomer/UpdateCustomer", ReplyAction="http://tempuri.org/IServiceCustomer/UpdateCustomerResponse")]
        System.Threading.Tasks.Task UpdateCustomerAsync(HelloWebClient.WcfServiceCustomerHost.Customer x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCustomer/DeleteCustomer", ReplyAction="http://tempuri.org/IServiceCustomer/DeleteCustomerResponse")]
        void DeleteCustomer(string customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCustomer/DeleteCustomer", ReplyAction="http://tempuri.org/IServiceCustomer/DeleteCustomerResponse")]
        System.Threading.Tasks.Task DeleteCustomerAsync(string customerId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCustomerChannel : HelloWebClient.WcfServiceCustomerHost.IServiceCustomer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCustomerClient : System.ServiceModel.ClientBase<HelloWebClient.WcfServiceCustomerHost.IServiceCustomer>, HelloWebClient.WcfServiceCustomerHost.IServiceCustomer {
        
        public ServiceCustomerClient() {
        }
        
        public ServiceCustomerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCustomerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCustomerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCustomerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddCustomer(string fName, string lName, string eMail, int tel) {
            base.Channel.AddCustomer(fName, lName, eMail, tel);
        }
        
        public System.Threading.Tasks.Task AddCustomerAsync(string fName, string lName, string eMail, int tel) {
            return base.Channel.AddCustomerAsync(fName, lName, eMail, tel);
        }
        
        public HelloWebClient.WcfServiceCustomerHost.Customer[] GetCustomerList() {
            return base.Channel.GetCustomerList();
        }
        
        public System.Threading.Tasks.Task<HelloWebClient.WcfServiceCustomerHost.Customer[]> GetCustomerListAsync() {
            return base.Channel.GetCustomerListAsync();
        }
        
        public HelloWebClient.WcfServiceCustomerHost.Customer GetCustomerByLastName(string lName) {
            return base.Channel.GetCustomerByLastName(lName);
        }
        
        public System.Threading.Tasks.Task<HelloWebClient.WcfServiceCustomerHost.Customer> GetCustomerByLastNameAsync(string lName) {
            return base.Channel.GetCustomerByLastNameAsync(lName);
        }
        
        public HelloWebClient.WcfServiceCustomerHost.Customer GetCustomerById(string Id) {
            return base.Channel.GetCustomerById(Id);
        }
        
        public System.Threading.Tasks.Task<HelloWebClient.WcfServiceCustomerHost.Customer> GetCustomerByIdAsync(string Id) {
            return base.Channel.GetCustomerByIdAsync(Id);
        }
        
        public void UpdateCustomer(HelloWebClient.WcfServiceCustomerHost.Customer x) {
            base.Channel.UpdateCustomer(x);
        }
        
        public System.Threading.Tasks.Task UpdateCustomerAsync(HelloWebClient.WcfServiceCustomerHost.Customer x) {
            return base.Channel.UpdateCustomerAsync(x);
        }
        
        public void DeleteCustomer(string customerId) {
            base.Channel.DeleteCustomer(customerId);
        }
        
        public System.Threading.Tasks.Task DeleteCustomerAsync(string customerId) {
            return base.Channel.DeleteCustomerAsync(customerId);
        }
    }
}
